Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'lib/seeder.rb'
    - 'script/**/*'
    - 'bin/**/*'
    - 'app/dashboards/**/*'
    - 'app/controllers/admin/**/*'
    - '**/*.orig'
    - '**/*.BACKUP*'
    - '**/*.BASE*'
    - '**/*.REMOTE*'
    - '**/*.LOCAL*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_sql
    - find_by_invitation_token
