Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'lib/middleware/sabayon.rb'
    - 'node_modules/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
    - 'config/initializers/devise.rb'

Style/FileName:
  Exclude:
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'lib/seeder.rb'
    - 'app/controllers/caregivers_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/answer/certification.rb'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/migrator/**/*'
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/seeder.rb'

Rails/DynamicFindBy:
  Whitelist:
    - find_by_sql
    - find_by_invitation_token
