---
version: 2
jobs:
  build:
    working_directory: ~/chirpyhire
    docker:
      - image: circleci/ruby:2.4.4-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: chirpyhire
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: chirpyhire
          POSTGRES_DB: chirpyhire
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      # Setup the environment
      - run: cp .sample.env .env
      - run: sudo apt-get update -y
      - run: sudo apt-get install g++ qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
      - run: bundle install

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rspec