# rubocop:disable Metrics/ModuleLength
module Nicknames
  class Generator
    def initialize(candidate)
      @candidate = candidate
      @organization = candidate.organization ||
                      Organization.find(candidate.organization_id)
    end

    def generate
      raise 'Unable to find new nickname' if
            organization.candidates.count > nickname_count
      loop do
        nickname = random_nickname
        return nickname unless taken?(nickname)
      end
    end

    def nickname_count
      ANIMALS.count * ADJECTIVES.count
    end

    private

    def taken?(nickname)
      organization.candidates.exists?(nickname: nickname)
    end

    def random_nickname
      "#{ADJECTIVES.sample} #{ANIMALS.sample}"
    end

    attr_reader :candidate, :organization
  end

  ANIMALS =
    %w(
      Aardvark
      Albatross
      Alligator
      Alpaca
      Anaconda
      Angelfish
      Anglerfish
      Ant
      Anteater
      Antelope
      Antlion
      Ape
      Aphid
      Armadillo
      Asp
      Baboon
      Badger
      Bandicoot
      Barnacle
      Barracuda
      Basilisk
      Bass
      Bat
      Beaver
      Bee
      Beetle
      Bison
      Blackbird
      Boa
      Bobcat
      Bonobo
      Buffalo
      Butterfly
      Buzzard
      Camel
      Capybara
      Cardinal
      Caribou
      Carp
      Caterpillar
      Catfish
      Centipede
      Chameleon
      Cheetah
      Chickadee
      Chimpanzee
      Chinchilla
      Chipmunk
      Clam
      Clownfish
      Cobra
      Cod
      Condor
      Constrictor
      Coral
      Cougar
      Cow
      Coyote
      Crab
      Crane
      Crawdad
      Crayfish
      Cricket
      Crocodile
      Cuckoo
      Cicada
      Deer
      Dingo
      Dolphin
      Dormouse
      Dove
      Dragonfly
      Dragon
      Eagle
      Earthworm
      Earwig
      Echidna
      Egret
      Elephant
      Elk
      Emu
      Ermine
      Falcon
      Ferret
      Finch
      Firefly
      Fish
      Flamingo
      Flyingfish
      Fowl
      Fox
      Frog
      Gazelle
      Gecko
      Gerbil
      Gibbon
      Giraffe
      Goldfish
      Gopher
      Gorilla
      Grasshopper
      Haddock
      Halibut
      Hamster
      Hare
      Hawk
      Hedgehog
      Heron
      Herring
      Hippopotamus
      Hornet
      Hummingbird
      Hyena
      Iguana
      Impala
      Jackal
      Jaguar
      Jellyfish
      Kangaroo
      Kingfisher
      Kite
      Kiwi
      Koala
      Ladybug
      Lark
      Lemming
      Lemur
      Leopard
      Lion
      Lizard
      Llama
      Lobster
      Lynx
      Macaw
      Mackerel
      Magpie
      Manatee
      Mandrill
      Marlin
      Marmoset
      Marmot
      Marsupial
      Marten
      Mastodon
      Meadowlark
      Meerkat
      Mockingbird
      Mongoose
      Monkey
      Moose
      Mouse
      Mule
      Muskox
      Narwhal
      Nightingale
      Ocelot
      Octopus
      Opossum
      Orangutan
      Orca
      Ostrich
      Otter
      Owl
      Ox
      Panda
      Panther
      Parakeet
      Parrot
      Partridge
      Peacock
      Pelican
      Penguin
      Pheasant
      Piranha
      Platypus
      Pony
      Porcupine
      Porpoise
      Puffin
      Puma
      Quail
      Quokka
      Raccoon
      Rattlesnake
      Raven
      Reindeer
      Rhinoceros
      Roadrunner
      Rooster
      Salamander
      Salmon
      Scorpion
      Seahorse
      Sparrow
      Squirrel
      Starfish
      Stingray
      Stoat
      Stork
      Swallow
      Swan
      Swift
      Swordfish
      Tapir
      Tarantula
      Tarsier
      Tern
      Thrush
      Tiger
      Tortoise
      Toucan
      Tuna
      Turtle
      Wallaby
      Walrus
      Wasp
      Warbler
      Weasel
      Whale
      Wildcat
      Wildebeest
      Wolf
      Wolverine
      Wombat
      Woodpecker
      Wren
      Yak
      Zebra
    ).freeze
  ADJECTIVES =
    [
      'Adaptable',
      'Adventurous',
      'Affable',
      'Affectionate',
      'Agreeable',
      'Ambitious',
      'Amiable',
      'Amicable',
      'Amusing',
      'Brave',
      'Bright',
      'Calm',
      'Careful',
      'Charming',
      'Communicative',
      'Compassionate ',
      'Confident',
      'Conscientious',
      'Considerate',
      'Convivial',
      'Courageous',
      'Courteous',
      'Creative',
      'Decisive',
      'Determined',
      'Diligent',
      'Diplomatic',
      'Discreet',
      'Dynamic',
      'Easygoing',
      'Emotional',
      'Energetic',
      'Enthusiastic',
      'Exuberant',
      'Faithful',
      'Fearless',
      'Forceful',
      'Frank',
      'Friendly',
      'Funny',
      'Generous',
      'Gentle',
      'Good',
      'Gregarious',
      'Helpful',
      'Honest',
      'Humorous',
      'Imaginative',
      'Impartial',
      'Independent',
      'Intellectual',
      'Intelligent',
      'Intuitive',
      'Inventive',
      'Kind',
      'Loving',
      'Loyal',
      'Modest',
      'Neat',
      'Nice',
      'Optimistic',
      'Passionate',
      'Patient',
      'Persistent',
      'Pioneering',
      'Philosophical',
      'Placid',
      'Plucky',
      'Polite',
      'Powerful',
      'Practical',
      'Quiet',
      'Rational',
      'Reliable',
      'Reserved',
      'Resourceful',
      'Romantic',
      'Sensible',
      'Sensitive',
      'Shy',
      'Sincere',
      'Sociable',
      'Straightforward',
      'Sympathetic',
      'Thoughtful',
      'Tidy',
      'Tough',
      'Unassuming',
      'Understanding',
      'Versatile',
      'Warmhearted',
      'Willing',
      'Witty'
    ].freeze

  private_constant :ANIMALS, :ADJECTIVES
end
# rubocop:enable Metrics/ModuleLength
